name: Lambdas deploy
on:
  push: 
    branches: ["main"]
  check_run:
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get .
  deploy-to-dev:
    name: Deploy develop
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Use Go
        run: echo "here deploy"
